version: '3.8'

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/usr/src/app
    ports:
      - 8004:8000
    env_file:
      - dev.env
    depends_on:
      - web-db

  web-db:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    expose:
      - 5432
    env_file:
      - dev.env
